name: CI

on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.5
      - name: Install Poetry
        run: |
          python -m pip install poetry==1.8.2
      - name: Configure Poetry
        run: |
          python -m poetry config virtualenvs.in-project true
      - name: View poetry version
        run: |
          poetry --version
      - name: Cache the virtualenv
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: |
          python -m poetry install
      - name: Run tests
        run: |
          python -m poetry run pytest
